name: enigma_cli
description: A simple command-line interface for encrypting and decrypting data.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  args: ^2.4.2
  enigma:
    git:
      url: https://github.com/carlosmakin/enigma.git
      ref: main
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
